fixtures:
  repositories:
    concat: https://github.com/puppetlabs/puppetlabs-concat.git
    postgresql: https://github.com/puppetlabs/puppetlabs-postgresql.git
    stdlib: https://github.com/puppetlabs/puppetlabs-stdlib.git
  symlinks:
    openerp: "#{source_dir}"
