#!/bin/sh
### BEGIN INIT INFO
# Provides: openerp
# Required-Start: $local_fs $remote_fs $network $syslog $postgresql
# Required-Stop: $local_fs $remote_fs $network $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# X-Interactive: false
# Short-Description: Start/stop OpenERP server and WebClient
### END INIT INFO

. /lib/lsb/init-functions

BASE="/srv/openerp/instances"

openerp() {

  instances=$(ls ${BASE} | wc -l)
  if [ $instances -eq 0 ]; then
    echo 'No instance seems to be installed'
    exit 1
  fi

  if [ -n $2 ]; then
    if [ ! -d "${BASE}/$2" ]; then
      echo "Unable to find auto-run for $2"
      log_end_msg 1
      exit 1
    fi
    p=$(ls ${BASE}/$2/auto-run/)
  else 
    p=$(ls ${BASE}/*/auto-run/ 2>/dev/null || echo 'none')
  fi
  for srv in $p; do
    if [ -f $srv ]; then
      $srv $1;
    else
      echo "$srv seems to be broken"
    fi
  done
} 

case $1 in 
  start|stop)
  openerp $1 $2
  ;;
  *)
  echo "$0 start|stop"
  exit 1
  ;;
esac
exit 0
