#!/bin/sh
### BEGIN INIT INFO
# Provides: openerp
# Required-Start: $local_fs $remote_fs $network $syslog $postgresql
# Required-Stop: $local_fs $remote_fs $network $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# X-Interactive: false
# Short-Description: Start/stop OpenERP server and WebClient
### END INIT INFO

. /lib/lsb/init-functions

BASE="/srv/openerp/instances"

openerp() {
  action=$1
  shift
  instances="$@"

  if [ -z "$instances" ]; then
    instances=$(ls ${BASE}/)
  fi
  
  for instance in ${instances}; do
    if [ -d "${BASE}/${instance}" ]; then
      openerp_instance $action $instance
    else
      log_failure_msg "instance not found: ${instance}"
    fi
  done
}

openerp_instance() {
  action=$1
  instance=$2

  if [ -d ${BASE}/${instance}/auto-run ]; then
    openerp_autorun $action $instance
  elif [ -x ${BASE}/${instance}/bin/supervisord ]; then
    openerp_supervisord $action $instance
  else
    log_failure_msg "no auto-run directory or supervisord found: ${instance}"
  fi
}

openerp_autorun() {
  action=$1
  instance=$2

  autorun_link=$(find ${BASE}/${instance}/auto-run -type l)
  if [ ! -z ${autorun_link} ]; then
    su -c "${autorun_link} ${action}" openerp
    if [ $? -eq 0 ]; then
      log_success_msg "instance ${action} successful: ${instance}"
    else
      log_failure_msg "auto-run script failed: ${instance}";
    fi
  fi

}

openerp_supervisord() {
  action=$1
  instance=$2

  supervisord="${BASE}/${instance}/bin/supervisord"
  supervisorctl="${BASE}/${instance}/bin/supervisorctl"
  supervisor_sock="${BASE}/${instance}/var/supervisord.sock"

  case $action in
    start)
    if [ ! -S ${supervisor_sock} ]; then
      su -c "${supervisord}" openerp
      if [ $? -eq 0 ]; then
        log_success_msg "instance ${action} successful: ${instance}"
      else
        log_failure_msg "failed to start supervisord: ${instance}"
      fi
    else
      log_warning_msg "instance already running: ${instance}"
    fi
    ;;
    stop)
    if [ -S ${supervisor_sock} ]; then
      su -c "${supervisorctl} shutdown" openerp
      if [ $? -eq 0 ]; then
        log_success_msg "instance ${action} successful: ${instance}"
      else
        log_failure_msg "failed to shutdown supervisord: ${instance}"
      fi
    else
      log_warning_msg "instance not running: ${instance}"
    fi
  esac
}

case $1 in
  start|stop)
  openerp $@
  ;;
  restart)
  shift
  openerp stop $@
  sleep 2
  openerp start $@
  ;;
  *)
  echo "$0 start|stop|restart"
  exit 1
  ;;
esac
exit 0
